### ISSUE TITLE
 To-do list

### ISSUE THREAD

**Issue by RicardoBritoBrens** [danysalas/WebDevChatRoom#3]
- [ ] El servidor debe de retornar los mensajes que recibe a todos los clientes conectados.
- [ ] El Cliente debe de tener la opción de poder desconectarse
- [ ] Un cliente conectado debe de poder enviar un mensaje a otro cliente (Mensaje Directo).

NOTA 1: Recuerden editar esta lista e indicar cual sera la tarea que van a atender.

NOTA 2 : Hasta el momento son todas las tareas que recuerdo están pendiente, si quedo alguna fuera por favor agregarla.
